name: DevSecOps - Test, Security and Deploy

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:
    name: Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar Pytest
        env:
          PYTHONPATH: .
        run: |
          pytest -v

  security:
    name: Bandit and Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python para Bandit
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit==1.8.6

      - name: Ejecutar Bandit
        run: |
          bandit -r app

      - name: Construir imagen Docker
        run: |
          docker build -t devsecops-api:${{ github.sha }} .

      - name: Ejecutar Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "devsecops-api:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "HIGH,CRITICAL"

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Deploy to EC2
    needs:
      - test
      - security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy por SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/devsecops-sre
            git pull origin main
            docker compose up -d --build
